### ISSUE TITLE
Questions about 'SCCA_SCCA' function

### ISSUE THREAD

**Issue by FaxinZ** [alexjamesing/mscca-regression-code#1]
Thank you for your code sharing! The data I'm analyzing now drives me to use sparse CCA. While I was reading 'SCCA_SCCA.m', some augments confused me:
- Augment `Spar1` and `Spar2` were annotated as 'sparsity constraint', and '0.5' was set for both of them in the published paper (Ing, 2019). I'm wondering why is this and how to select these number according to different type of data;
- Furthermore, I also a bit doubt the augment `w1_sign` and `w2_sign`, and expect some further explanation if it's convenient.
Looking forward to your reply!

**Comment by alexjamesing** [comment]
Hi Faxin,
Thanks for your interest in the code. 
First speaking very broadly for context: Spar 1 and Spar 2 are user defined hyper parameters. They are often set by grid search e.g. you could use 10 different values for Spar 1 and 10 for Spar 2, giving 100 possible choices, you could then select the hyper parameters that resulted in the highest correlation and use these. The best way to do this would be using some kind of cross-validation procedure. The crucial consideration here is to take appropriate steps to separate the hyper-parameter selection procedure from any statistical inferences you carry out on the data. This is exactly the same process that would be used to select hyper-parameters in e.g. a LASSO regression (see any introductory Machine Learning book for more information). 
To be more specific about our choices here: We found that stability selection helped to produce more robust results (please see the paper referenced in our study for more details). As this procedure is reasonably insensitive to the L1 (here labelled Spar 1 and Spar 2 for data-views 1 and 2 respectively), you can just set the L1 value at a set level. Here, we selected 0.5 simply as this is the mid point of the regularisation path (i.e. mid way between 0 and 1). We then selected a conservative stability selection threshold of 0.9 (the higher end of what is recommended, again see the referenced paper for more details).
w1_sign and w2_sign are simply constraints you can put on the weights if you want them to be all positive or all negative. E.g. if you expect an inverse relation between two data-sets (as we did, expecting grey matter to be inversely associated with psychiatric symptoms), you can set one of them to positive (1) and one to negative (-1). If you do not have a hypothesis like this, just set them to 0.
I hope this helps?
All the best,
Alex

**Comment by FaxinZ** [comment]
Hi Alex,

Thank you for your patient reply, that helps me a lot! (And sorry for my carelessness when I skimmed the method part, really missed so much useful information.)

And another tricky thing for me is that I'm now processing a subject-level time series data (i.e. the row of the dependent/independent data matrix is 'time point' rather than 'subject'). It seems impractical to use the cross-validation procedure as well as the stability selection procedure you mentioned, because it is unreasonable to resample. Thus wondering if there's any intuition on stability control of time series sCCA modeling?

**Comment by alexjamesing** [comment]
HI Faxin, 
Unfortunately, I am not aware of anything like that. Note that I am now closing this as an 'issue'. If you have further questions, please email me at alexing1421@gmail.com and reserve this 'issues' section for any problems with the code. 
Best
Alex

**Comment by FaxinZ** [comment]
Get that, thank you anyway!
